### ISSUE TITLE
The images on the main page

### ISSUE THREAD

**Issue by amazein** [sbgn/sbgn#1]
I do not see some images on the main page. 
See attached. 
![screenshot](https://cloud.githubusercontent.com/assets/19857097/15980186/a858a290-2f69-11e6-85ea-59b43f9049ff.png)

**Comment by vtoure** [comment]
The figures have been added. Works now.

**Comment by amazein** [comment]
Thanks, Vasundra. Some more comments:

1st image: is it possible to make the quality better and probably make the image a bit smaller?

2nd image: it is not possible to read it. Then, if you click on the diagram you would expect to move to a larger image. There is a link bellow the diagram which leads to the page from which one can download images but it requires some more clicks. Probably we can make it easier to see the diagram?

Another option: making the 2nd image larger so it is possible to read the labels?
