### ISSUE TITLE
[PD] Precisions about cardinality on production arc

### ISSUE THREAD

**Issue by ghost** [sbgn/sbgn#10]
Section 2.9.1 of SBGN PD L1 V3, on consumption arc, features a long description of the optional cardinality, and mention production arc. In section 2.9.2, on production arc, we have only "A cardinality label can be associated with a production arc indicating the stoichiometry of a process".  Could we add:
"For more details, see the section describing the consumption arc".  Alternatively, there could be section "Arc cardinality".

NB: In both consumption and production arc section, "the stoichiometry of a process" should be replaced by  "the stoichiometry of the relevant EPN for the process".

**Comment by ghost** [comment]
Sorry, I meant L1V1.3

**Comment by amazein** [comment]
This needs to be moved to the PD specification issues https://github.com/sbgn/process-descriptions/issues

**Comment by amazein** [comment]
@Adrienrougny: Probably we should move it to Trello or PD spec issues and close this issue here?

**Comment by adrienrougny** [comment]
> @Adrienrougny: Probably we should move it to Trello or PD spec issues and close this issue here?

Maybe just to PD spec for now, since we haven't really decided how to move the issues to Trello yet.

**Comment by amazein** [comment]
Moved to PD Issues
