### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by prozion** [sbgn/sbgn#16]
Following links on the page https://github.com/sbgn/sbgn/wiki/SBGN_ML don't work:

-  http://sbgn.org/libsbgn/0.2
-  http://sbgn.org/libsbgn/pd/0.1
-  https://github.com/LibSBGN/Exchange_Format_(as_discussed_around_SBGN5.5)

**Comment by amazein** [comment]
Thank you, Denis 
@fbergmann I have access to fix but I do not know where these links should lead.

**Comment by fbergmann** [comment]
i would say: 

* http://sbgn.org/libsbgn/0.2 -> https://raw.githubusercontent.com/sbgn/libsbgn/milestone-2/resources/SBGN.xsd
* http://sbgn.org/libsbgn/pd/0.1 -> https://raw.githubusercontent.com/sbgn/libsbgn/milestone-1/resources/SBGN.xsd
* https://github.com/LibSBGN/Exchange_Format_(as_discussed_around_SBGN5.5) -> https://github.com/sbgn/sbgn/wiki/SBGN_ML

**Comment by amazein** [comment]
The first two are opening to a text file in my browser. Probably not how it was intended?
The last one simply directs to the same page where the text is, does not make sense, I guess...
I have not created or ever edited this page, probably someone could take charge and update?

**Comment by fbergmann** [comment]
well the issue of the first two links is that they are the xml namespaces of an SBGN-ML document, as such they do not need to be resolvable. I would have assumed that the original links on sbgn.org pointed to the xsds. For me they don't download files but display in the browser, then it would not be the raw link but something like: 

https://github.com/sbgn/libsbgn/blob/milestone-1/resources/SBGN.xsd

the other link might refer to: 

https://github.com/sbgn/sbgn/wiki/SBGN5.5_LibSBGN_Minutes

**Comment by amazein** [comment]
Do you want to replace the links as you prefer? I believe you have edit access to all sbgn repositories.

**Comment by fbergmann** [comment]
while that can be done, I thought we were here talking about establishing redirects. As you can see on this issue: 

https://github.com/sbgn/sbgn.github.io/issues/13

some people are confusing XML namespaces with resolvable urls, and having those redirects in place for the first 2 entries would be helpful. 

I can edit the document, to change them there.

**Comment by amazein** [comment]
By redirects, do you mean this type?
https://github.com/sbgn/sbgn/blob/gh-pages/docs/LibSBGN.md

**Comment by fbergmann** [comment]
yes indeed

**Comment by amazein** [comment]
We can create similar files in this folder
https://github.com/sbgn/sbgn/tree/gh-pages/docs

**Comment by amazein** [comment]
@fbergmann Please let me know if you would like me to introduce the changes, I just need instructions on how you would like to have it because I am not familiar with the content of the LibSBGN part.

**Comment by fbergmann** [comment]
i've changed the SBGN_ML page, but it would still be great if we could get the redirects going, though i'm not sure how the gh-pages/docs stuff works.

**Comment by amazein** [comment]
I can do that, I just need information from what URL to what URL, then files can be created directly in the browser, they will look like this one:
https://github.com/sbgn/sbgn/blob/gh-pages/docs/redirect/LibSBGN.md

**Comment by fbergmann** [comment]
I think we should have these in place: 

* http://sbgn.org/libsbgn/0.2 -> https://raw.githubusercontent.com/sbgn/libsbgn/milestone-2/resources/SBGN.xsd
* http://sbgn.org/libsbgn/pd/0.1 -> https://raw.githubusercontent.com/sbgn/libsbgn/milestone-1/resources/SBGN.xsd

as when people are looking for the xml namespace, they will probably expect to find a schema. If you do these i can then do the same for 0.3 files once we are done with it.

**Comment by amazein** [comment]
Added new redirects, do not work properly for some reason
https://github.com/sbgn/sbgn/tree/gh-pages/docs/redirects

**Comment by fbergmann** [comment]
it works precisely as intended for me ... thank you

**Comment by amazein** [comment]
When I put http://sbgn.org/libsbgn/0.2  in a browser, it does not redirect me to https://raw.githubusercontent.com/sbgn/libsbgn/milestone-2/resources/SBGN.xsd

**Comment by fbergmann** [comment]
that must be browser dependent .. some browsers download the file, others will display it. i think either of it is fine, as users get the sbgn ml schema they need.
