### ISSUE TITLE
Issue on "Software support"

### ISSUE THREAD

**Issue by tczauderna** [sbgn/sbgn#18]
The "Software support" page (https://sbgn.github.io/software) has three issues in "Databases and collections of SBGN maps".

MetaCrop has been generated using SBGN-ED.

Path2Models has not been generated by JWS.
It has been generated using a number of tools including PathVisio and SBGN-ED.

RIMAS has been generated using SBGN-ED (Vanted itself would not be sufficient for this).

**Comment by adrienrougny** [comment]
Thanks for pointing out the issues!
The page was corrected.
