### ISSUE TITLE
Reference cards

### ISSUE THREAD

**Issue by amazein** [sbgn/sbgn#2]
Reference cards are probably the most useful downloads. Should we make them easy to find? Probably even have it in the list on the left? Earlier we had templates for PowerPoint, high quality images in different formats. Now it is only PNG? http://www.sbgn.org/User_Page

**Comment by huaiyumi** [comment]
Reference cards are in the templates link with multiple formats. For people who are not familiar with SBGN, they won't be able to know what ref card means. The template link is embedded in the Learn to use SBGN page, which we believe is the right location.

**Comment by amazein** [comment]
Okay, probably it is just me downloading templates and reference cards all the time.
By the way, there is no link to templates or reference cards there http://sbgn.github.io/sbgn/docs/learn_to_use_sbgn, I just checked.

**Comment by vtoure** [comment]
The link is on the word "Templates" (if you pass you mouse on, you can see it). 
But I also added a link in the following sentence for a better search.
