### ISSUE TITLE
The images on the first page

### ISSUE THREAD

**Issue by amazein** [sbgn/sbgn#4]
1st image: is it possible to make the quality better and probably make the image a bit smaller?

2nd image: it is not possible to read it. Then, if you click on the diagram you would expect to move to a larger image. There is a link bellow the diagram which leads to the page from which one can download images but it requires some more clicks. Probably we can make it easier to see the diagram?

Another option: making the 2nd image larger so it is possible to read the labels?

**Comment by vtoure** [comment]
1st image: it is possible to make it smaller. I can't answer for the quality (it's a png file).

2nd image: right click - View image - opens to the larger diagram. Making the image larger with readable labels will be as it was before: really big image and not elegant on the webpage.

**Comment by huaiyumi** [comment]
For the 2nd image, there is a "click here" link so that you can reach a more detailed page with larger image.

**Comment by amazein** [comment]
Yes, I mentioned that link too. I just think it would be more intuitive if you click on an image and the next you see is an enlarged version.

**Comment by amazein** [comment]
The welcome page was redesigned completely since then.
